//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: disktracking.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// the disk tracking service definition
///
/// Usage: instantiate `Disktracking_DiskTrackingServiceClient`, then call methods of this protocol to make API calls.
internal protocol Disktracking_DiskTrackingServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol? { get }

  func streamDiskPositions(
    _ request: Disktracking_DiskPosition,
    callOptions: CallOptions?,
    handler: @escaping (Disktracking_DiskPositions) -> Void
  ) -> ServerStreamingCall<Disktracking_DiskPosition, Disktracking_DiskPositions>
}

extension Disktracking_DiskTrackingServiceClientProtocol {
  internal var serviceName: String {
    return "disktracking.DiskTrackingService"
  }

  /// Server streaming call to StreamDiskPositions
  ///
  /// - Parameters:
  ///   - request: Request to send to StreamDiskPositions.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func streamDiskPositions(
    _ request: Disktracking_DiskPosition,
    callOptions: CallOptions? = nil,
    handler: @escaping (Disktracking_DiskPositions) -> Void
  ) -> ServerStreamingCall<Disktracking_DiskPosition, Disktracking_DiskPositions> {
    return self.makeServerStreamingCall(
      path: Disktracking_DiskTrackingServiceClientMetadata.Methods.streamDiskPositions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamDiskPositionsInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Disktracking_DiskTrackingServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Disktracking_DiskTrackingServiceNIOClient")
internal final class Disktracking_DiskTrackingServiceClient: Disktracking_DiskTrackingServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the disktracking.DiskTrackingService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Disktracking_DiskTrackingServiceNIOClient: Disktracking_DiskTrackingServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the disktracking.DiskTrackingService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// the disk tracking service definition
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Disktracking_DiskTrackingServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol? { get }

  func makeStreamDiskPositionsCall(
    _ request: Disktracking_DiskPosition,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Disktracking_DiskPosition, Disktracking_DiskPositions>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Disktracking_DiskTrackingServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Disktracking_DiskTrackingServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeStreamDiskPositionsCall(
    _ request: Disktracking_DiskPosition,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Disktracking_DiskPosition, Disktracking_DiskPositions> {
    return self.makeAsyncServerStreamingCall(
      path: Disktracking_DiskTrackingServiceClientMetadata.Methods.streamDiskPositions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamDiskPositionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Disktracking_DiskTrackingServiceAsyncClientProtocol {
  internal func streamDiskPositions(
    _ request: Disktracking_DiskPosition,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Disktracking_DiskPositions> {
    return self.performAsyncServerStreamingCall(
      path: Disktracking_DiskTrackingServiceClientMetadata.Methods.streamDiskPositions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamDiskPositionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Disktracking_DiskTrackingServiceAsyncClient: Disktracking_DiskTrackingServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Disktracking_DiskTrackingServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'streamDiskPositions'.
  func makeStreamDiskPositionsInterceptors() -> [ClientInterceptor<Disktracking_DiskPosition, Disktracking_DiskPositions>]
}

internal enum Disktracking_DiskTrackingServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "DiskTrackingService",
    fullName: "disktracking.DiskTrackingService",
    methods: [
      Disktracking_DiskTrackingServiceClientMetadata.Methods.streamDiskPositions,
    ]
  )

  internal enum Methods {
    internal static let streamDiskPositions = GRPCMethodDescriptor(
      name: "StreamDiskPositions",
      path: "/disktracking.DiskTrackingService/StreamDiskPositions",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// the disk tracking service definition
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Disktracking_DiskTrackingServiceProvider: CallHandlerProvider {
  var interceptors: Disktracking_DiskTrackingServiceServerInterceptorFactoryProtocol? { get }

  func streamDiskPositions(request: Disktracking_DiskPosition, context: StreamingResponseCallContext<Disktracking_DiskPositions>) -> EventLoopFuture<GRPCStatus>
}

extension Disktracking_DiskTrackingServiceProvider {
  internal var serviceName: Substring {
    return Disktracking_DiskTrackingServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StreamDiskPositions":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Disktracking_DiskPosition>(),
        responseSerializer: ProtobufSerializer<Disktracking_DiskPositions>(),
        interceptors: self.interceptors?.makeStreamDiskPositionsInterceptors() ?? [],
        userFunction: self.streamDiskPositions(request:context:)
      )

    default:
      return nil
    }
  }
}

/// the disk tracking service definition
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Disktracking_DiskTrackingServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Disktracking_DiskTrackingServiceServerInterceptorFactoryProtocol? { get }

  func streamDiskPositions(
    request: Disktracking_DiskPosition,
    responseStream: GRPCAsyncResponseStreamWriter<Disktracking_DiskPositions>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Disktracking_DiskTrackingServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Disktracking_DiskTrackingServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Disktracking_DiskTrackingServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Disktracking_DiskTrackingServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StreamDiskPositions":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Disktracking_DiskPosition>(),
        responseSerializer: ProtobufSerializer<Disktracking_DiskPositions>(),
        interceptors: self.interceptors?.makeStreamDiskPositionsInterceptors() ?? [],
        wrapping: { try await self.streamDiskPositions(request: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

internal protocol Disktracking_DiskTrackingServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'streamDiskPositions'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStreamDiskPositionsInterceptors() -> [ServerInterceptor<Disktracking_DiskPosition, Disktracking_DiskPositions>]
}

internal enum Disktracking_DiskTrackingServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "DiskTrackingService",
    fullName: "disktracking.DiskTrackingService",
    methods: [
      Disktracking_DiskTrackingServiceServerMetadata.Methods.streamDiskPositions,
    ]
  )

  internal enum Methods {
    internal static let streamDiskPositions = GRPCMethodDescriptor(
      name: "StreamDiskPositions",
      path: "/disktracking.DiskTrackingService/StreamDiskPositions",
      type: GRPCCallType.serverStreaming
    )
  }
}
